-- CreateTable
CREATE TABLE `approvisionnement` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_Entreprise` INTEGER NULL,
    `ID_Fournisseur` INTEGER NULL,
    `ID_Produit` INTEGER NULL,
    `RESTOCKING_DATE` DATE NOT NULL,
    `QUANTITY` INTEGER NOT NULL,

    INDEX `ID_Entreprise`(`ID_Entreprise`),
    INDEX `ID_Fournisseur`(`ID_Fournisseur`),
    INDEX `ID_Produit`(`ID_Produit`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `client` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(255) NOT NULL,
    `LAST_NAME` VARCHAR(255) NOT NULL,
    `ADRESSE` VARCHAR(255) NOT NULL,
    `CITY` VARCHAR(255) NOT NULL,
    `PHONE_NUMBER` INTEGER NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `PHONE_NUMBER`(`PHONE_NUMBER`),
    UNIQUE INDEX `EMAIL`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `entreprise` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `SIEGE_SOCIAL` VARCHAR(255) NOT NULL,
    `CREATION_DATE` DATE NOT NULL,
    `FISCAL_IDENTITY` VARCHAR(255) NOT NULL,
    `CAPITAL` INTEGER NOT NULL,
    `EMPLOYEES_NUMBER` INTEGER NOT NULL,
    `CITY` VARCHAR(255) NOT NULL,
    `CEO` VARCHAR(255) NOT NULL,
    `NUMERO_TELEPHONE` INTEGER NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `NUMERO_TELEPHONE`(`NUMERO_TELEPHONE`),
    UNIQUE INDEX `EMAIL`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `facture` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_Client` INTEGER NULL,
    `ID_Entreprise` INTEGER NULL,
    `QUANTITY` INTEGER NOT NULL,

    INDEX `ID_Client`(`ID_Client`),
    INDEX `ID_Entreprise`(`ID_Entreprise`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `facture_product` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_Facture` INTEGER NULL,
    `ID_Product` INTEGER NULL,
    `QUANTITY` INTEGER NOT NULL,

    INDEX `ID_Facture`(`ID_Facture`),
    INDEX `ID_Product`(`ID_Product`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `fournisseur` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `ADRESSE` VARCHAR(255) NOT NULL,
    `CITY` VARCHAR(255) NOT NULL,
    `PHONE_NUMBER` INTEGER NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `PHONE_NUMBER`(`PHONE_NUMBER`),
    UNIQUE INDEX `EMAIL`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `product` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `BUYING_PRICE` INTEGER NOT NULL,
    `SELLING_PRICE` INTEGER NOT NULL,
    `MARGIN_RATE` DECIMAL(65, 30) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
